from __future__ import annotations

import json
import threading
from collections.abc import Iterator
from contextlib import contextmanager
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer

from kinekt.embeddings import embed_text
from kinekt.generation import generate_agent_reply


class _OllamaHandler(BaseHTTPRequestHandler):
    requests: list[dict[str, object]] = []

    def do_POST(self) -> None:  # noqa: N802
        length = int(self.headers.get("Content-Length", "0"))
        payload = json.loads(self.rfile.read(length).decode("utf-8"))
        self.requests.append(payload)
        if self.path == "/api/embeddings":
            response = {"embedding": [0.25, 0.5, 0.75]}
        elif self.path == "/api/generate":
            response = {"response": "Generated by the loopback integration fixture."}
        else:
            self.send_error(404)
            return
        body = json.dumps(response).encode("utf-8")
        self.send_response(200)
        self.send_header("Content-Type", "application/json")
        self.send_header("Content-Length", str(len(body)))
        self.end_headers()
        self.wfile.write(body)

    def log_message(self, _format: str, *_args: object) -> None:
        return


@contextmanager
def _ollama_fixture() -> Iterator[str]:
    _OllamaHandler.requests = []
    server = ThreadingHTTPServer(("127.0.0.1", 0), _OllamaHandler)
    thread = threading.Thread(target=server.serve_forever, daemon=True)
    thread.start()
    try:
        yield f"http://127.0.0.1:{server.server_port}"
    finally:
        server.shutdown()
        thread.join(timeout=5)
        server.server_close()


def test_real_loopback_http_contract_for_embeddings_and_generation(monkeypatch) -> None:
    with _ollama_fixture() as base_url:
        monkeypatch.setenv("KINEKT_EMBEDDING_BACKEND", "ollama")
        monkeypatch.setenv("KINEKT_OLLAMA_URL", f"{base_url}/api/embeddings")
        monkeypatch.setenv("KINEKT_GENERATION_BACKEND", "ollama")
        monkeypatch.setenv("KINEKT_OLLAMA_GENERATE_URL", f"{base_url}/api/generate")

        assert embed_text("local context") == [0.25, 0.5, 0.75]
        generation = generate_agent_reply(
            workspace="/workspace",
            session_id="integration",
            user_message="What is indexed?",
            hits=[],
            prior_user_count=0,
        )

    assert generation.backend == "ollama"
    assert generation.text == "Generated by the loopback integration fixture."
    assert len(_OllamaHandler.requests) == 2
